"""How a scientific output LANDS on disk (GW-30 / review item 10).

Nothing here is about the numbers in an export; it is about the file a consumer
opens.  Two properties, both of which the writers used to break:

  * **a 2.1 file identifies as 2.1 from the first byte.**  The 2.1 writers
    delegated to the 2.0 writer, so the destination briefly held a
    complete-looking ``gwcat-pe-2.0`` file; the validation summary was then
    generated by READING THAT FILE BACK; and only afterwards were 2.1 and the
    contract attrs patched on with ``h5py.File(out, "r+")``.  The summary
    therefore described a file that never existed in its final form, and a
    failure between the two steps published a 2.0 file where a 2.1 one was
    asked for.
  * **an export is written atomically.**  Both writers opened the FINAL path
    with ``h5py.File(path, "w")``, which truncates on the first byte.  Any
    failure during the write -- a bad column, a full disk, a SIGINT -- destroyed
    the previous good export and left a truncated HDF5 file where a consumer
    expects a complete one.

Fixtures are a tiny synthetic store built directly with h5py (the suite's
per-file-fixture convention), plus a hand-built selection product: no network,
no ingest, no production artifact.
"""
import os

import numpy as np
import h5py
import pytest

from gwcat.catalog import GWCatalog
from gwcat.export import ExportProduct, build_pe_product, get_exporter

DARKSIRENS_PARAMS = ["mass_1", "mass_2", "luminosity_distance", "ra", "dec",
                     "chi_eff", "p_dL_pe"]

_SELECTION_COLUMNS = ["m1det", "m2det", "dL", "chieff", "ra", "dec",
                      "m1src", "m2src", "redshift", "pdraw"]


def _build_store(tmp_path, n=64, H0=67.74, Om0=0.3089, seed=3,
                 name="store.h5"):
    """Two-BBH synthetic store matching the on-disk schema GWCatalog reads."""
    rng = np.random.default_rng(seed)
    names = ["GW930001_000001", "GW930002_000002"]
    cols = {p: [] for p in DARKSIRENS_PARAMS}
    offsets = [0]
    for _ in names:
        cols["mass_1"].append(rng.uniform(20, 45, n))
        cols["mass_2"].append(rng.uniform(8, 20, n))
        cols["luminosity_distance"].append(rng.uniform(300, 800, n))
        cols["ra"].append(rng.uniform(0, 2 * np.pi, n))
        cols["dec"].append(rng.uniform(-np.pi / 2, np.pi / 2, n))
        cols["chi_eff"].append(rng.uniform(-0.3, 0.3, n))
        cols["p_dL_pe"].append(rng.uniform(0.1, 1.0, n))
        offsets.append(offsets[-1] + n)

    path = tmp_path / name
    with h5py.File(path, "w") as f:
        f.attrs["schema_version"] = "1.2"
        f.attrs["param_names"] = np.array(DARKSIRENS_PARAMS,
                                          dtype=h5py.string_dtype())
        idx = f.create_group("index")
        idx.create_dataset("offsets", data=np.array(offsets, dtype="i8"))
        idx.create_dataset("event_names",
                           data=np.array(names, dtype=h5py.string_dtype()))
        mg = f.create_group("meta")
        for k in ["source_class", "compact_type"]:
            mg.create_dataset(k, data=np.array(["BBH"] * len(names),
                                               dtype=h5py.string_dtype()))
        for k, v in [("far", 5e-4), ("far_available", 1.0), ("pastro", 0.99),
                     ("p_astro", 0.99), ("dL_prior_H0", H0),
                     ("dL_prior_Om0", Om0)]:
            mg.create_dataset(k, data=np.full(len(names), v, dtype="f8"))
        sg = f.create_group("samples")
        for p in DARKSIRENS_PARAMS:
            sg.create_dataset(p, data=np.concatenate(cols[p]))
    return str(path)


def _pe_product(tmp_path, **kwargs):
    store = _build_store(tmp_path, **kwargs)
    return build_pe_product(GWCatalog(store), spin_basis="chieff", nsamp=8,
                            seed=0)


def _selection_product(n=5):
    """A hand-built selection product -- the writer owns only serialization,
    so nothing about this test needs a real injection campaign."""
    cols = {k: np.linspace(1.0, 2.0, n) for k in _SELECTION_COLUMNS}
    attrs = {"spin_basis": "component", "far_threshold": 1.0,
             "cosmology_H0": 67.74, "cosmology_Om0": 0.3089}
    return ExportProduct(kind="selection", columns=cols, attrs=attrs,
                         spin_basis="component",
                         summary={"n_injections": int(n)})


def _leftover_temps(tmp_path):
    return [p.name for p in tmp_path.iterdir() if "gwcat-tmp" in p.name]


# ==========================================================================
# 1. A 2.1 export is never published as 2.0
# ==========================================================================
@pytest.mark.parametrize("kind,fmt,expected", [
    ("pe", "gwcat2.1", "gwcat-pe-2.1"),
    ("selection", "gwcat2.1", "gwcat-selection-2.1"),
    ("pe", "gwcat2", "gwcat-pe-2.0"),
    ("selection", "gwcat2", "gwcat-selection-2.0"),
])
def test_the_summary_sees_the_version_the_file_will_keep(
        tmp_path, monkeypatch, kind, fmt, expected):
    """The summary is generated from the FINISHED file.

    The 2.1 writers used to produce their summary while the file on disk still
    said 2.0 and carried no contract attrs, so a 2.1 export's summary was
    indistinguishable from a 2.0 one -- and any summary field reconstructed
    from the file described the wrong version of it.
    """
    import gwcat.validation_summary as vs

    seen = {}
    real = vs.write_validation_summary

    def spy(out_path, summary, *args, **kwargs):
        with h5py.File(out_path, "r") as f:
            seen["on_disk"] = f.attrs["format_version"]
            seen["has_contract"] = "contract_hash" in f.attrs
        seen["summary"] = dict(summary)
        return real(out_path, summary, *args, **kwargs)

    monkeypatch.setattr(vs, "write_validation_summary", spy)

    product = (_pe_product(tmp_path) if kind == "pe"
               else _selection_product())
    out = tmp_path / f"{kind}_{fmt}.h5"
    get_exporter(fmt, kind=kind)(product, str(out), write_summary=True)

    assert seen["on_disk"] == expected
    assert seen["has_contract"] is (fmt == "gwcat2.1")
    # ...and the summary SAYS which version it describes.
    assert seen["summary"]["format_version"] == expected

    with h5py.File(out, "r") as f:
        assert f.attrs["format_version"] == expected


def test_a_21_export_writes_its_file_exactly_once(tmp_path, monkeypatch):
    """No reopen-and-patch: one open, one published file.

    ``h5py.File(out, "r+")`` on the destination was the mechanism by which the
    version was mutated after publication; a 2.1 write must not need it.
    """
    opened = []
    real_file = h5py.File

    def spy(name, mode="r", *args, **kwargs):
        opened.append((str(name), mode))
        return real_file(name, mode, *args, **kwargs)

    product = _pe_product(tmp_path)
    out = tmp_path / "once.h5"
    monkeypatch.setattr(h5py, "File", spy)
    get_exporter("gwcat2.1", kind="pe")(product, str(out))
    monkeypatch.undo()

    writes = [(p, m) for p, m in opened if m in ("w", "a", "r+")]
    assert len(writes) == 1, f"expected one write-open, got {writes}"
    # ...and it was NOT the destination: the file is published by rename.
    assert writes[0][0] != str(out)


# ==========================================================================
# 2. Atomic writes
# ==========================================================================
#: A column each kind writes in the MIDDLE of its dataset order, so corrupting
#: it makes the write fail with some datasets already on disk and some not --
#: the half-written file the atomic rename exists to prevent.
_MIDWAY_COLUMN = {"pe": "dL", "selection": "chieff"}


def _break(product, kind):
    """Make the write fail midway: a dtype h5py has no HDF5 equivalent for."""
    product.columns[_MIDWAY_COLUMN[kind]] = np.array([object()], dtype=object)
    return product


@pytest.mark.parametrize("kind,fmt", [("pe", "gwcat2"), ("pe", "gwcat2.1"),
                                      ("selection", "gwcat2"),
                                      ("selection", "gwcat2.1")])
def test_a_failed_export_leaves_the_previous_one_untouched(tmp_path, kind, fmt):
    """The destination is either the old file or the new one, never a mixture.

    ``h5py.File(out_path, "w")`` truncated the good export on the first byte, so
    a failure partway through replaced a valid input to somebody's inference run
    with a file holding whichever datasets happened to be written already.
    """
    product = (_pe_product(tmp_path) if kind == "pe"
               else _selection_product())
    writer = get_exporter(fmt, kind=kind)
    out = tmp_path / f"good_{kind}_{fmt}.h5"
    writer(product, str(out))
    good_bytes = out.read_bytes()

    with pytest.raises(Exception):
        writer(_break(product, kind), str(out))

    assert out.read_bytes() == good_bytes, \
        "a failed export overwrote the previous good file"
    assert _leftover_temps(tmp_path) == []


@pytest.mark.parametrize("kind,fmt", [("pe", "gwcat2"), ("selection", "gwcat2.1")])
def test_an_interrupted_export_does_not_create_the_output_at_all(tmp_path, kind,
                                                                 fmt):
    """When there is no previous file, a failed export must leave none.

    A half-written file at the expected path is worse than a missing one: a
    consumer opens it, and only the *contents* say something is wrong.
    """
    product = (_pe_product(tmp_path) if kind == "pe"
               else _selection_product())
    out = tmp_path / f"never_{kind}.h5"
    with pytest.raises(Exception):
        get_exporter(fmt, kind=kind)(_break(product, kind), str(out))
    assert not out.exists()
    assert _leftover_temps(tmp_path) == []


def test_keyboardinterrupt_during_a_write_is_not_swallowed(tmp_path):
    """Ctrl-C must propagate AND still clean up -- an except-Exception cleanup
    would have let a partial file survive the one interruption users actually
    hit."""
    from gwcat.export.atomic import atomic_output_path

    out = tmp_path / "interrupted.h5"
    with pytest.raises(KeyboardInterrupt):
        with atomic_output_path(out) as tmp:
            with h5py.File(tmp, "w") as f:
                f.create_dataset("x", data=np.arange(4.0))
            raise KeyboardInterrupt
    assert not out.exists()
    assert _leftover_temps(tmp_path) == []


def test_the_temp_file_is_a_sibling_of_the_destination(tmp_path):
    """The rename that publishes the file must not cross a filesystem, so the
    temp file lives in the DESTINATION directory -- not in /tmp."""
    from gwcat.export.atomic import atomic_output_path

    dest = tmp_path / "sub"
    dest.mkdir()
    out = dest / "x.h5"
    with atomic_output_path(out) as tmp:
        assert str(tmp) != str(out)
        with h5py.File(tmp, "w") as f:
            f.create_dataset("x", data=np.arange(4.0))
        assert os.path.dirname(os.path.abspath(tmp)) == str(dest)
        assert (dest / os.path.basename(tmp)).exists()
    assert out.exists()
    assert _leftover_temps(dest) == []


def test_a_successful_export_leaves_no_temp_files(tmp_path):
    product = _pe_product(tmp_path)
    out = tmp_path / "clean.h5"
    get_exporter("gwcat2.1", kind="pe")(product, str(out),
                                        write_summary=True)
    assert out.exists()
    assert _leftover_temps(tmp_path) == []
