"""Generate ``usf_mpmath_reference.json`` (GW-40i).

Independent high-precision reference for the UniformSourceFrame (and
UniformComovingVolume) luminosity-distance density of a flat matter + Lambda
cosmology (no radiation -- ``FlatLambdaCDM(H0, Om0)``, what gwcat builds for
every declared prior cosmology):

    p(dL) = [D_C(z)^2 / (E(z) (1+z)^td)] / (dD_L/dz) / Z,
    Z     = INT_{z(dmin)}^{z(dmax)} D_C^2 / (E (1+z)^td) dz,
    D_C   = (c/H0) INT_0^z dz'/E(z'),   E = sqrt(Om0 (1+z)^3 + 1 - Om0),

with ``z(dL)`` by mpmath ``findroot`` and every integral by mpmath tanh-sinh,
at 40 digits.  Shares no code with :mod:`gwcat.cosmology`.

Run (needs mpmath)::

    python tests/fixtures/make_usf_mpmath_reference.py
"""
import json
import os
import sys
from multiprocessing import Pool

import mpmath as mp

OUT = os.path.join(os.path.dirname(os.path.abspath(__file__)),
                   "usf_mpmath_reference.json")
C_KMS = "299792.458"
DPS = 40

#: (H0, Om0, name): LAL Planck15 (the O4 / OD-2 prior cosmology), astropy
#: Planck15's (H0, Om0) as a bare FlatLambdaCDM, and a round test cosmology.
COSMOLOGIES = [(67.90, 0.3065, "Planck15_LAL"),
               (67.74, 0.3075, "astropy_Planck15_H0_Om0"),
               (70.0, 0.3, "round")]
#: Declared prior bounds [dmin, dmax] in Mpc, spanning the releases' range.
BOUNDS = [(1.0, 15000.0), (10.0, 10000.0), (100.0, 30000.0), (1.0, 1000.0),
          (10.0, 50000.0)]


def _funcs(H0, Om0):
    H0 = mp.mpf(H0)
    Om = mp.mpf(Om0)
    dH = mp.mpf(C_KMS) / H0

    def E(z):
        return mp.sqrt(Om * (1 + z) ** 3 + (1 - Om))

    def dc(z):
        return dH * mp.quad(lambda x: 1 / E(x), [0, z])

    def zof(d):
        d = mp.mpf(d)
        if d == 0:
            return mp.mpf(0)
        return mp.findroot(lambda z: (1 + z) * dc(z) - d,
                           d / dH / (1 + d / dH / 2),
                           tol=mp.mpf(10) ** (-DPS + 5))

    def shape(z, td):
        c = dc(z)
        e = E(z)
        num = c * c / e / ((1 + z) if td else 1)
        return num / (c + (1 + z) * dH / e)

    def norm(dmin, dmax, td):
        zl, zh = zof(dmin), zof(dmax)
        return mp.quad(lambda z: dc(z) ** 2 / E(z) / ((1 + z) if td else 1),
                       mp.linspace(zl, zh, 9))
    return zof, shape, norm


def job(args):
    H0, Om0, dmin, dmax, td, dLs = args
    with mp.workdps(DPS):
        zof, shape, norm = _funcs(H0, Om0)
        Z = norm(mp.mpf(dmin), mp.mpf(dmax), td)
        return [mp.nstr(shape(zof(mp.mpf(d)), td) / Z, 25) for d in dLs]


def dl_points(dmin, dmax):
    pts = [0.5 * dmin, dmin, dmin * 1.0001, 2.0 * dmin, 3.0, 40.0, 440.0,
           2500.0, 0.5 * dmax, 0.99 * dmax, dmax, 1.3 * dmax]
    k = 25
    r = (dmax / dmin) ** (1.0 / (k - 1))
    pts += [dmin * r ** i for i in range(k)]
    return sorted({float(p) for p in pts if p > 0})


def main():
    jobs = []
    for H0, Om0, name in COSMOLOGIES:
        for dmin, dmax in BOUNDS:
            for td in (True, False):
                jobs.append((H0, Om0, dmin, dmax, td, dl_points(dmin, dmax)))
    with Pool(min(len(jobs), os.cpu_count() or 1)) as pool:
        res = pool.map(job, jobs)
    rows = []
    for (H0, Om0, dmin, dmax, td, dLs), ps in zip(jobs, res):
        rows.append({"H0": H0, "Om0": Om0, "dmin": dmin, "dmax": dmax,
                     "time_dilation": td, "dL": dLs, "p": ps})
    doc = {"description": ("mpmath reference values of the UniformSourceFrame "
                           "(time_dilation=true) / UniformComovingVolume dL "
                           "density of FlatLambdaCDM(H0, Om0), normalised over "
                           "[dmin, dmax] and evaluated also outside it. "
                           "Generated by make_usf_mpmath_reference.py."),
           "mpmath_version": mp.__version__, "dps": DPS, "rows": rows}
    with open(OUT, "w") as f:
        json.dump(doc, f, indent=0)
        f.write("\n")
    print(f"wrote {len(rows)} blocks to {OUT}", file=sys.stderr)


if __name__ == "__main__":
    main()
